
name: Python based Playwright tests refactored

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  create-virtualenv-and-run-tests:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    # - name: create virtual env 
    #   run: |
    #     pip install virtualenv
    #     python -m venv env
    #     source env/bin/activate
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install playwright
        pip install pytest
        pip install pytest-playwright
        playwright install
    - name : run tests
      run: |
        python3 -m pytest -s tests/test_search_DuckduckGo.py
      
        
