
name: Python based Playwright tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: create virtual env & install dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        sudo python3 -m pip install --upgrade pip
        sudo pip install -r requirements.txt
        sudo pip install playwright
        sudo pip install pytest
        sudo pip install pytest-playwright
    - name: Install browsers 
      run: |
        playwright install
    - name: Run pytest tests
      run: |
        python3 -m pytest tests/test_search_DuckduckGo.py
