
name: Python based Playwright tests with docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  setup-docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: addnab/docker-run-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        registry: docker.io
        image: sunjeet81/docker_python_playwright:dockerplaywright-from-scratch   
        run: |
          echo '~~~~~~ !!! Kicking off Tests now !!! ~~~~~'
          python -m pytest tests/ --browser webkit
          ls

  # create-virtualenv-and-run-tests:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python 3.10
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: "3.10"
  #   - name: create virtual env 
  #     run: |
  #       pip install virtualenv
  #       python -m venv env
  #       source env/bin/activate
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install -r requirements.txt
  #       pip install playwright
  #       pip install pytest
  #       pip install pytest-playwright
  #       playwright install
  #   - name : run tests
  #     run: |
  #       python -m pytest -s tests/ 

