
name: Python based Playwright tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: create virtual env 
      run: |
        python3 -m venv venv
        source venv/bin/activate
        
    - name : installl dependencies and run tests
      run: |
        #weird but apparently true , have to initiate v env again between run steps !!
        #source venv/bin/activate
        sudo python3 -m pip install --upgrade pip
        sudo pip install -r requirements.txt
        sudo pip install playwright
        sudo pip install pytest
        sudo pip install pytest-playwright
        sudo playwright install
        python3 -m pytest -s tests/test_search_DuckduckGo.py
      
        
